const $=s=>document.querySelector(s);
const search=$('#certificateSearch'), category=$('#certificateCategory'), grid=$('#certificateGrid');
let certificates=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=f=>'assets/certificates/'+encodeURIComponent(f).replace(/%2F/g,'/');
const isImage=f=>/\.(png|jpe?g|webp|gif)$/i.test(f||'');
function render(){if(!grid)return;const q=(search?.value||'').toLowerCase(),cat=category?.value||'all';const items=certificates.filter(c=>(`${c.title} ${c.issuer}`.toLowerCase().includes(q))&&(cat==='all'||c.category===cat));if(!items.length){grid.innerHTML='<article class="certificate-empty"><h3>No certificates found</h3><p>Try another search or category.</p></article>';return}grid.innerHTML=items.map(c=>{const u=url(c.file);const preview=isImage(c.file)?`<img src="${u}" alt="${esc(c.title)} certificate" loading="lazy">`:`<div class="certificate-pdf-preview"><span>PDF</span><small>${esc(c.issuer||'Certificate')}</small></div>`;return `<article class="certificate-card"><a class="certificate-preview-link" href="${u}" target="_blank" rel="noopener">${preview}</a><h3>${esc(c.title)}</h3><p>${esc(c.issuer||'Certificate')}</p><span class="certificate-tag">${esc((c.category||'other').replace(/\b\w/g,m=>m.toUpperCase()))}</span><a href="${u}" target="_blank" rel="noopener">View Certificate →</a></article>`}).join('')}
async function load(){if(!grid)return;try{const r=await fetch('assets/certificates/certificates.json',{cache:'no-store'});if(!r.ok)throw Error(r.status);certificates=await r.json();render()}catch(e){grid.innerHTML='<article class="certificate-empty"><h3>Certificate gallery</h3><p>Upload the certificate files listed in <code>certificates.json</code> and publish the folder to GitHub Pages.</p></article>'}}
search?.addEventListener('input',render);category?.addEventListener('change',render);load();
